//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugTable()
        {
            this.DrugIngredientRelationship = new HashSet<DrugIngredientRelationship>();
        }
    
        public System.Guid DrugId { get; set; }
        public string DrugEnglishName { get; set; }
        public string DrugCommodityName { get; set; }
        public string DrugCommonName { get; set; }
        public string DrugSpecification { get; set; }
        public string DrugMerchant { get; set; }
        public string DrugRemark1 { get; set; }
        public string DrugRemark2 { get; set; }
        public long InsertTime { get; set; }
        public long UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugIngredientRelationship> DrugIngredientRelationship { get; set; }
        public virtual DrugTable DrugTable1 { get; set; }
        public virtual DrugTable DrugTable2 { get; set; }
    }
}
