//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugIngredientRelationship
    {
        public System.Guid RelationshipId { get; set; }
        public System.Guid DrugId { get; set; }
        public System.Guid IngredientID { get; set; }
        public long InsertTime { get; set; }
        public long LastUpdateTime { get; set; }
    
        public virtual DrugTable DrugTable { get; set; }
        public virtual IngredientTable IngredientTable { get; set; }
    }
}
