//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientsInWhichDrugs_View
    {
        public System.Guid IngredientID { get; set; }
        public string IngredientCNName { get; set; }
        public string IngredientShortName { get; set; }
        public System.Guid DrugId { get; set; }
        public string DrugEnglishName { get; set; }
        public string DrugCommodityName { get; set; }
        public string DrugCommonName { get; set; }
        public string DrugSpecification { get; set; }
        public string DrugMerchant { get; set; }
        public string DrugRemark1 { get; set; }
        public string DrugRemark2 { get; set; }
        public System.Guid RelationshipId { get; set; }
        public string CPName { get; set; }
        public string USPName { get; set; }
        public string EPName { get; set; }
        public string JPName { get; set; }
        public string IngredientAlias { get; set; }
        public long InsertTime { get; set; }
        public long LastUpdateTime { get; set; }
    }
}
