//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngredientTable()
        {
            this.DrugIngredientRelationship = new HashSet<DrugIngredientRelationship>();
        }
    
        public System.Guid IngredientID { get; set; }
        public string IngredientCNName { get; set; }
        public string IngredientShortName { get; set; }
        public string CPName { get; set; }
        public string USPName { get; set; }
        public string EPName { get; set; }
        public string JPName { get; set; }
        public string IngredientAlias { get; set; }
        public long InsertTime { get; set; }
        public long LastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugIngredientRelationship> DrugIngredientRelationship { get; set; }
    }
}
